export const companies = [
  {
    companyName: "Microsoft",
    foundedYear: 1975,
    HQ: "Redmond, WA, USA",
    Industry: "Enterprise Software",
    totalFunding: "$1B",
    ARR: "$270B",
    Valuation: "$3T",
    Employees: "221,000",
    topInvestors: "Bill Gates, Paul Allen",
    Product: "Azure, Office 365, Teams",
    g2Rating: 4.4,
  },
  {
    companyName: "Salesforce",
    foundedYear: 1999,
    HQ: "San Francisco, CA, USA",
    Industry: "CRM",
    totalFunding: "$65.4M",
    ARR: "$37.9B",
    Valuation: "$227.8B",
    Employees: "75,000",
    topInvestors: "Halsey Minor, Larry Ellison",
    Product: "Sales Cloud, Service Cloud",
    g2Rating: 4.3,
  },
  {
    companyName: "Adobe",
    foundedYear: 1982,
    HQ: "San Jose, CA, USA",
    Industry: "Creative Software",
    totalFunding: "$2.5M",
    ARR: "$19.4B",
    Valuation: "$240B",
    Employees: "29,945",
    topInvestors: "Hambrecht & Quist",
    Product: "Creative Cloud, Document Cloud",
    g2Rating: 4.5,
  },
  {
    companyName: "Oracle",
    foundedYear: 1977,
    HQ: "Austin, TX, USA",
    Industry: "Database & Enterprise",
    totalFunding: "$2K",
    ARR: "$52.9B",
    Valuation: "$350B",
    Employees: "143,000",
    topInvestors: "Larry Ellison, Bob Miner",
    Product: "Oracle Cloud, NetSuite",
    g2Rating: 4,
  },
  {
    companyName: "SAP",
    foundedYear: 1972,
    HQ: "Walldorf, Germany",
    Industry: "Enterprise Software",
    totalFunding: "N/A",
    ARR: "$32.5B",
    Valuation: "$215B",
    Employees: "107,415",
    topInvestors: "Dietmar Hopp, Klaus Tschira",
    Product: "S/4HANA, SuccessFactors",
    g2Rating: 4.1,
  },
  {
    companyName: "Intuit",
    foundedYear: 1983,
    HQ: "Mountain View, CA, USA",
    Industry: "Financial Software",
    totalFunding: "$273M",
    ARR: "$14.4B",
    Valuation: "$180B",
    Employees: "18,200",
    topInvestors: "Sierra Ventures, Kleiner Perkins",
    Product: "QuickBooks, TurboTax",
    g2Rating: 4.4,
  },
  {
    companyName: "ServiceNow",
    foundedYear: 2004,
    HQ: "Santa Clara, CA, USA",
    Industry: "IT Service Management",
    totalFunding: "$82.5M",
    ARR: "$8.9B",
    Valuation: "$147B",
    Employees: "20,000",
    topInvestors: "JMI Equity, Sequoia Capital",
    Product: "IT Service Management Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Workday",
    foundedYear: 2005,
    HQ: "Pleasanton, CA, USA",
    Industry: "HR & Finance",
    totalFunding: "$249.9M",
    ARR: "$7.3B",
    Valuation: "$65B",
    Employees: "18,800",
    topInvestors: "Greylock Partners, NEA",
    Product: "HCM, Financial Management",
    g2Rating: 4.2,
  },
  {
    companyName: "Zoom",
    foundedYear: 2011,
    HQ: "San Jose, CA, USA",
    Industry: "Video Communications",
    totalFunding: "$145.5M",
    ARR: "$4.5B",
    Valuation: "$85B",
    Employees: "7,388",
    topInvestors: "Sequoia Capital, Emergence",
    Product: "Video Conferencing Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Shopify",
    foundedYear: 2006,
    HQ: "Ottawa, Canada",
    Industry: "E-commerce",
    totalFunding: "$122.3M",
    ARR: "$7.1B",
    Valuation: "$95B",
    Employees: "11,600",
    topInvestors: "Bessemer, FirstMark, Felicis",
    Product: "E-commerce Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Atlassian",
    foundedYear: 2002,
    HQ: "Sydney, Australia",
    Industry: "Collaboration Software",
    totalFunding: "$60M",
    ARR: "$3.5B",
    Valuation: "$55B",
    Employees: "11,800",
    topInvestors: "Accel Partners",
    Product: "Jira, Confluence, Trello",
    g2Rating: 4.3,
  },
  {
    companyName: "Snowflake",
    foundedYear: 2012,
    HQ: "Bozeman, MT, USA",
    Industry: "Data Warehousing",
    totalFunding: "$1.4B",
    ARR: "$2.8B",
    Valuation: "$75B",
    Employees: "6,500",
    topInvestors: "Sequoia, ICONIQ, Altimeter",
    Product: "Cloud Data Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "HubSpot",
    foundedYear: 2006,
    HQ: "Cambridge, MA, USA",
    Industry: "Marketing & Sales",
    totalFunding: "$100.5M",
    ARR: "$2.2B",
    Valuation: "$32B",
    Employees: "7,600",
    topInvestors: "General Catalyst, Google Ventures",
    Product: "Marketing Hub, Sales Hub",
    g2Rating: 4.4,
  },
  {
    companyName: "DocuSign",
    foundedYear: 2003,
    HQ: "San Francisco, CA, USA",
    Industry: "Digital Agreements",
    totalFunding: "$514.3M",
    ARR: "$2.5B",
    Valuation: "$10B",
    Employees: "7,336",
    topInvestors: "Kleiner Perkins, Accel",
    Product: "eSignature, Contract Lifecycle",
    g2Rating: 4.5,
  },
  {
    companyName: "Slack",
    foundedYear: 2009,
    HQ: "San Francisco, CA, USA",
    Industry: "Team Communication",
    totalFunding: "$1.4B",
    ARR: "$1.7B",
    Valuation: "$27.7B (Salesforce)",
    Employees: "2,545",
    topInvestors: "Accel, Andreessen Horowitz",
    Product: "Team Messaging Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Notion",
    foundedYear: 2013,
    HQ: "San Francisco, CA, USA",
    Industry: "Productivity",
    totalFunding: "$353M",
    ARR: "$400M",
    Valuation: "$10B",
    Employees: 800,
    topInvestors: "Index Ventures, Sequoia",
    Product: "All-in-one workspace",
    g2Rating: 4.7,
  },
  {
    companyName: "Datadog",
    foundedYear: 2010,
    HQ: "New York, NY, USA",
    Industry: "Monitoring & Analytics",
    totalFunding: "$147.9M",
    ARR: "$2.1B",
    Valuation: "$44B",
    Employees: "5,200",
    topInvestors: "ICONIQ, Index Ventures",
    Product: "Infrastructure Monitoring",
    g2Rating: 4.4,
  },
  {
    companyName: "MongoDB",
    foundedYear: 2007,
    HQ: "New York, NY, USA",
    Industry: "Database",
    totalFunding: "$311.2M",
    ARR: "$1.7B",
    Valuation: "$26B",
    Employees: "4,500",
    topInvestors: "Sequoia, NEA, USV",
    Product: "Document Database Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Okta",
    foundedYear: 2009,
    HQ: "San Francisco, CA, USA",
    Industry: "Identity Management",
    totalFunding: "$230.5M",
    ARR: "$2.2B",
    Valuation: "$25B",
    Employees: "5,900",
    topInvestors: "Andreessen Horowitz, Greylock",
    Product: "Identity & Access Management",
    g2Rating: 4.4,
  },
  {
    companyName: "Twilio",
    foundedYear: 2008,
    HQ: "San Francisco, CA, USA",
    Industry: "Communications",
    totalFunding: "$261.3M",
    ARR: "$4.1B",
    Valuation: "$12B",
    Employees: "7,867",
    topInvestors: "Bessemer, Union Square",
    Product: "Communications APIs",
    g2Rating: 4.3,
  },
  {
    companyName: "Stripe",
    foundedYear: 2010,
    HQ: "San Francisco, CA, USA",
    Industry: "Payments",
    totalFunding: "$8.7B",
    ARR: "$14B",
    Valuation: "$65B",
    Employees: "8,000",
    topInvestors: "Sequoia, Andreessen Horowitz",
    Product: "Payment Processing Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Square",
    foundedYear: 2009,
    HQ: "San Francisco, CA, USA",
    Industry: "Payments",
    totalFunding: "$590.5M",
    ARR: "$19.7B",
    Valuation: "$85B",
    Employees: "8,500",
    topInvestors: "Khosla Ventures, Sequoia",
    Product: "Payment & POS Solutions",
    g2Rating: 4.2,
  },
  {
    companyName: "Palantir",
    foundedYear: 2003,
    HQ: "Denver, CO, USA",
    Industry: "Data Analytics",
    totalFunding: "$2.6B",
    ARR: "$2.2B",
    Valuation: "$52B",
    Employees: "3,500",
    topInvestors: "Founders Fund, In-Q-Tel",
    Product: "Data Integration Platform",
    g2Rating: 4,
  },
  {
    companyName: "Canva",
    foundedYear: 2013,
    HQ: "Sydney, Australia",
    Industry: "Design",
    totalFunding: "$572.6M",
    ARR: "$2B",
    Valuation: "$40B",
    Employees: "3,500",
    topInvestors: "Sequoia, Bessemer, Bond",
    Product: "Design Platform",
    g2Rating: 4.7,
  },
  {
    companyName: "Monday.com",
    foundedYear: 2012,
    HQ: "Tel Aviv, Israel",
    Industry: "Work Management",
    totalFunding: "$234.1M",
    ARR: "$736M",
    Valuation: "$14B",
    Employees: "1,900",
    topInvestors: "Sapphire Ventures, Insight",
    Product: "Work OS Platform",
    g2Rating: 4.6,
  },
  {
    companyName: "Asana",
    foundedYear: 2008,
    HQ: "San Francisco, CA, USA",
    Industry: "Work Management",
    totalFunding: "$453.2M",
    ARR: "$652M",
    Valuation: "$5.5B",
    Employees: "1,600",
    topInvestors: "Benchmark, Founders Fund",
    Product: "Work Management Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Airtable",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "Database/Spreadsheet",
    totalFunding: "$735.1M",
    ARR: "$500M",
    Valuation: "$11B",
    Employees: 900,
    topInvestors: "Benchmark, Thrive Capital",
    Product: "Low-code Database Platform",
    g2Rating: 4.6,
  },
  {
    companyName: "Figma",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "Design",
    totalFunding: "$332.9M",
    ARR: "$600M",
    Valuation: "$20B (Adobe)",
    Employees: "1,300",
    topInvestors: "Index Ventures, Greylock",
    Product: "Collaborative Design Tool",
    g2Rating: 4.7,
  },
  {
    companyName: "GitLab",
    foundedYear: 2011,
    HQ: "San Francisco, CA, USA",
    Industry: "DevOps",
    totalFunding: "$435.6M",
    ARR: "$580M",
    Valuation: "$8B",
    Employees: "2,300",
    topInvestors: "ICONIQ, Goldman Sachs",
    Product: "DevOps Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Zendesk",
    foundedYear: 2007,
    HQ: "San Francisco, CA, USA",
    Industry: "Customer Service",
    totalFunding: "$85.5M",
    ARR: "$1.9B",
    Valuation: "$13.2B",
    Employees: "6,000",
    topInvestors: "Benchmark, Matrix Partners",
    Product: "Customer Service Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Box",
    foundedYear: 2005,
    HQ: "Redwood City, CA, USA",
    Industry: "Cloud Storage",
    totalFunding: "$562.4M",
    ARR: "$1B",
    Valuation: "$3.5B",
    Employees: "2,800",
    topInvestors: "DFJ, NEA, Bessemer",
    Product: "Cloud Content Management",
    g2Rating: 4.2,
  },
  {
    companyName: "Dropbox",
    foundedYear: 2008,
    HQ: "San Francisco, CA, USA",
    Industry: "Cloud Storage",
    totalFunding: "$1.7B",
    ARR: "$2.5B",
    Valuation: "$8.5B",
    Employees: "2,700",
    topInvestors: "Sequoia, Accel, Index",
    Product: "Cloud Storage & Collaboration",
    g2Rating: 4.4,
  },
  {
    companyName: "Freshworks",
    foundedYear: 2010,
    HQ: "San Mateo, CA, USA",
    Industry: "Customer Engagement",
    totalFunding: "$484.7M",
    ARR: "$596M",
    Valuation: "$5.2B",
    Employees: "5,000",
    topInvestors: "Accel, Sequoia Capital India",
    Product: "Customer Engagement Suite",
    g2Rating: 4.4,
  },
  {
    companyName: "Klaviyo",
    foundedYear: 2012,
    HQ: "Boston, MA, USA",
    Industry: "Marketing Automation",
    totalFunding: "$778.2M",
    ARR: "$698M",
    Valuation: "$9.5B",
    Employees: "1,500",
    topInvestors: "Summit Partners, Accel",
    Product: "Email & SMS Marketing",
    g2Rating: 4.6,
  },
  {
    companyName: "UiPath",
    foundedYear: 2005,
    HQ: "New York, NY, USA",
    Industry: "RPA",
    totalFunding: "$2B",
    ARR: "$1.3B",
    Valuation: "$7B",
    Employees: "4,013",
    topInvestors: "Sequoia, Accel, IVP",
    Product: "Robotic Process Automation",
    g2Rating: 4.5,
  },
  {
    companyName: "Databricks",
    foundedYear: 2013,
    HQ: "San Francisco, CA, USA",
    Industry: "Data & AI",
    totalFunding: "$3.5B",
    ARR: "$1.6B",
    Valuation: "$43B",
    Employees: "5,000",
    topInvestors: "Andreessen Horowitz, NEA",
    Product: "Unified Analytics Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Confluent",
    foundedYear: 2014,
    HQ: "Mountain View, CA, USA",
    Industry: "Data Streaming",
    totalFunding: "$455.9M",
    ARR: "$773M",
    Valuation: "$9.1B",
    Employees: "2,500",
    topInvestors: "Sequoia, Benchmark, Index",
    Product: "Data Streaming Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "HashiCorp",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "Infrastructure",
    totalFunding: "$349.5M",
    ARR: "$541M",
    Valuation: "$13B",
    Employees: "2,200",
    topInvestors: "GV, Mayfield, IVP",
    Product: "Infrastructure Automation",
    g2Rating: 4.6,
  },
  {
    companyName: "Elastic",
    foundedYear: 2012,
    HQ: "Mountain View, CA, USA",
    Industry: "Search & Analytics",
    totalFunding: "$162M",
    ARR: "$1.1B",
    Valuation: "$8B",
    Employees: "3,000",
    topInvestors: "NEA, Benchmark, Index",
    Product: "Search & Analytics Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "PagerDuty",
    foundedYear: 2009,
    HQ: "San Francisco, CA, USA",
    Industry: "Incident Response",
    totalFunding: "$173.7M",
    ARR: "$430M",
    Valuation: "$2.8B",
    Employees: "1,000",
    topInvestors: "Andreessen Horowitz, Bessemer",
    Product: "Digital Operations Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "New Relic",
    foundedYear: 2008,
    HQ: "San Francisco, CA, USA",
    Industry: "Observability",
    totalFunding: "$215M",
    ARR: "$785M",
    Valuation: "$6.5B",
    Employees: "2,300",
    topInvestors: "Benchmark, Trinity, Tenaya",
    Product: "Observability Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Splunk",
    foundedYear: 2003,
    HQ: "San Francisco, CA, USA",
    Industry: "Data Analytics",
    totalFunding: "$40M",
    ARR: "$3.7B",
    Valuation: "$28B (Cisco)",
    Employees: "8,000",
    topInvestors: "August Capital, JK&B Capital",
    Product: "Data Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Cloudflare",
    foundedYear: 2009,
    HQ: "San Francisco, CA, USA",
    Industry: "Web Infrastructure",
    totalFunding: "$332.1M",
    ARR: "$1.6B",
    Valuation: "$28B",
    Employees: "3,266",
    topInvestors: "NEA, Venrock, Union Square",
    Product: "Web Performance & Security",
    g2Rating: 4.7,
  },
  {
    companyName: "SendGrid",
    foundedYear: 2009,
    HQ: "Denver, CO, USA",
    Industry: "Email Delivery",
    totalFunding: "$81M",
    ARR: "$200M",
    Valuation: "$3B (Twilio)",
    Employees: 600,
    topInvestors: "Bessemer, Foundry Group",
    Product: "Email Delivery Platform",
    g2Rating: 4,
  },
  {
    companyName: "Mailchimp",
    foundedYear: 2001,
    HQ: "Atlanta, GA, USA",
    Industry: "Email Marketing",
    totalFunding: "$0",
    ARR: "$1B",
    Valuation: "$12B (Intuit)",
    Employees: "1,200",
    topInvestors: "Bootstrapped",
    Product: "Marketing Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Miro",
    foundedYear: 2011,
    HQ: "San Francisco, CA, USA",
    Industry: "Collaboration",
    totalFunding: "$476.3M",
    ARR: "$400M",
    Valuation: "$17.5B",
    Employees: "1,800",
    topInvestors: "ICONIQ, Accel, GV",
    Product: "Visual Collaboration Platform",
    g2Rating: 4.7,
  },
  {
    companyName: "Grammarly",
    foundedYear: 2009,
    HQ: "San Francisco, CA, USA",
    Industry: "Writing Assistant",
    totalFunding: "$400M",
    ARR: "$300M",
    Valuation: "$13B",
    Employees: 600,
    topInvestors: "General Catalyst, IVP",
    Product: "AI Writing Assistant",
    g2Rating: 4.6,
  },
  {
    companyName: "Calendly",
    foundedYear: 2013,
    HQ: "Atlanta, GA, USA",
    Industry: "Scheduling",
    totalFunding: "$350.6M",
    ARR: "$100M",
    Valuation: "$3B",
    Employees: 700,
    topInvestors: "OpenView, ICONIQ",
    Product: "Scheduling Platform",
    g2Rating: 4.7,
  },
  {
    companyName: "Intercom",
    foundedYear: 2011,
    HQ: "San Francisco, CA, USA",
    Industry: "Customer Messaging",
    totalFunding: "$240.7M",
    ARR: "$200M",
    Valuation: "$1.3B",
    Employees: 800,
    topInvestors: "Kleiner Perkins, Bessemer",
    Product: "Customer Messaging Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Segment",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "Customer Data",
    totalFunding: "$284M",
    ARR: "$200M",
    Valuation: "$3.2B (Twilio)",
    Employees: 600,
    topInvestors: "Accel, GV, Kleiner Perkins",
    Product: "Customer Data Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Auth0",
    foundedYear: 2013,
    HQ: "Bellevue, WA, USA",
    Industry: "Identity",
    totalFunding: "$330M",
    ARR: "$200M",
    Valuation: "$6.5B (Okta)",
    Employees: 850,
    topInvestors: "Bessemer, Sapphire",
    Product: "Identity Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Looker",
    foundedYear: 2012,
    HQ: "Santa Cruz, CA, USA",
    Industry: "Business Intelligence",
    totalFunding: "$281.5M",
    ARR: "$150M",
    Valuation: "$2.6B (Google)",
    Employees: 800,
    topInvestors: "CapitalG, Kleiner Perkins",
    Product: "Data Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Amplitude",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "Product Analytics",
    totalFunding: "$336M",
    ARR: "$233M",
    Valuation: "$4B",
    Employees: 700,
    topInvestors: "Sequoia, IVP, Battery",
    Product: "Product Analytics Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Mixpanel",
    foundedYear: 2009,
    HQ: "San Francisco, CA, USA",
    Industry: "Product Analytics",
    totalFunding: "$77M",
    ARR: "$100M",
    Valuation: "$1.05B",
    Employees: 300,
    topInvestors: "Andreessen Horowitz, Sequoia",
    Product: "Product Analytics",
    g2Rating: 4.4,
  },
  {
    companyName: "Sumo Logic",
    foundedYear: 2010,
    HQ: "Redwood City, CA, USA",
    Industry: "Log Management",
    totalFunding: "$235M",
    ARR: "$299M",
    Valuation: "$2.3B",
    Employees: 750,
    topInvestors: "Accel, DFJ, Greylock",
    Product: "Cloud Log Management",
    g2Rating: 4.2,
  },
  {
    companyName: "Zscaler",
    foundedYear: 2008,
    HQ: "San Jose, CA, USA",
    Industry: "Cloud Security",
    totalFunding: "$148M",
    ARR: "$1.6B",
    Valuation: "$30B",
    Employees: "5,000",
    topInvestors: "TPG, Lightspeed",
    Product: "Cloud Security Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "CrowdStrike",
    foundedYear: 2011,
    HQ: "Austin, TX, USA",
    Industry: "Cybersecurity",
    totalFunding: "$481M",
    ARR: "$3.1B",
    Valuation: "$70B",
    Employees: "7,900",
    topInvestors: "Warburg Pincus, Accel",
    Product: "Endpoint Security Platform",
    g2Rating: 4.7,
  },
  {
    companyName: "Palo Alto Networks",
    foundedYear: 2005,
    HQ: "Santa Clara, CA, USA",
    Industry: "Cybersecurity",
    totalFunding: "$66.3M",
    ARR: "$7.5B",
    Valuation: "$95B",
    Employees: "13,300",
    topInvestors: "Sequoia, Greylock",
    Product: "Security Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "RingCentral",
    foundedYear: 2003,
    HQ: "Belmont, CA, USA",
    Industry: "Communications",
    totalFunding: "$44M",
    ARR: "$2.2B",
    Valuation: "$5B",
    Employees: "3,600",
    topInvestors: "Sequoia, Khosla, Scale",
    Product: "Cloud Communications",
    g2Rating: 4.2,
  },
  {
    companyName: "Five9",
    foundedYear: 2001,
    HQ: "San Ramon, CA, USA",
    Industry: "Contact Center",
    totalFunding: "$242M",
    ARR: "$787M",
    Valuation: "$8B",
    Employees: "2,800",
    topInvestors: "Adams Street, Partech",
    Product: "Contact Center Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Veeva Systems",
    foundedYear: 2007,
    HQ: "Pleasanton, CA, USA",
    Industry: "Life Sciences",
    totalFunding: "$7M",
    ARR: "$2.4B",
    Valuation: "$35B",
    Employees: "5,600",
    topInvestors: "Emergence Capital",
    Product: "Life Sciences Cloud",
    g2Rating: 4.3,
  },
  {
    companyName: "Coupa",
    foundedYear: 2006,
    HQ: "San Mateo, CA, USA",
    Industry: "Spend Management",
    totalFunding: "$169.5M",
    ARR: "$725M",
    Valuation: "$8B (Thoma Bravo)",
    Employees: "3,200",
    topInvestors: "Battery, Crosslink",
    Product: "Business Spend Management",
    g2Rating: 4.3,
  },
  {
    companyName: "Bill.com",
    foundedYear: 2006,
    HQ: "San Jose, CA, USA",
    Industry: "Financial Operations",
    totalFunding: "$402.7M",
    ARR: "$900M",
    Valuation: "$9B",
    Employees: "2,500",
    topInvestors: "Bank of America, TPG",
    Product: "Financial Operations Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Zoom Info",
    foundedYear: 2007,
    HQ: "Vancouver, WA, USA",
    Industry: "Sales Intelligence",
    totalFunding: "$241.7M",
    ARR: "$1.1B",
    Valuation: "$12B",
    Employees: "3,500",
    topInvestors: "TA Associates, Carlyle",
    Product: "Go-to-Market Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Smartsheet",
    foundedYear: 2005,
    HQ: "Bellevue, WA, USA",
    Industry: "Work Management",
    totalFunding: "$120.8M",
    ARR: "$880M",
    Valuation: "$8.4B (Vista/Blackstone)",
    Employees: "3,200",
    topInvestors: "Insight Partners, Madrona",
    Product: "Work Management Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Qualtrics",
    foundedYear: 2002,
    HQ: "Provo, UT, USA",
    Industry: "Experience Management",
    totalFunding: "$400M",
    ARR: "$1.5B",
    Valuation: "$12.5B (Silver Lake)",
    Employees: "5,300",
    topInvestors: "Sequoia, Accel, Insight",
    Product: "Experience Management Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Wix",
    foundedYear: 2006,
    HQ: "Tel Aviv, Israel",
    Industry: "Website Building",
    totalFunding: "$59M",
    ARR: "$1.6B",
    Valuation: "$10B",
    Employees: "5,500",
    topInvestors: "Benchmark, Bessemer",
    Product: "Website Builder Platform",
    g2Rating: 4.2,
  },
  {
    companyName: "Toast",
    foundedYear: 2011,
    HQ: "Boston, MA, USA",
    Industry: "Restaurant Tech",
    totalFunding: "$902M",
    ARR: "$3.9B",
    Valuation: "$20B",
    Employees: "4,500",
    topInvestors: "TCV, Tiger Global",
    Product: "Restaurant Management Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Gong",
    foundedYear: 2015,
    HQ: "San Francisco, CA, USA",
    Industry: "Revenue Intelligence",
    totalFunding: "$584M",
    ARR: "$250M",
    Valuation: "$7.3B",
    Employees: "1,300",
    topInvestors: "Sequoia, Coatue, Thrive",
    Product: "Revenue Intelligence Platform",
    g2Rating: 4.7,
  },
  {
    companyName: "Outreach",
    foundedYear: 2014,
    HQ: "Seattle, WA, USA",
    Industry: "Sales Engagement",
    totalFunding: "$489M",
    ARR: "$200M",
    Valuation: "$4.4B",
    Employees: "1,000",
    topInvestors: "Lone Pine, Meritech, Spark",
    Product: "Sales Engagement Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Salesloft",
    foundedYear: 2011,
    HQ: "Atlanta, GA, USA",
    Industry: "Sales Engagement",
    totalFunding: "$245M",
    ARR: "$200M",
    Valuation: "$2.3B",
    Employees: 900,
    topInvestors: "Insight Partners, HarbourVest",
    Product: "Sales Engagement Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Braze",
    foundedYear: 2011,
    HQ: "New York, NY, USA",
    Industry: "Customer Engagement",
    totalFunding: "$175M",
    ARR: "$420M",
    Valuation: "$5.6B",
    Employees: "1,300",
    topInvestors: "Spark Capital, NEA",
    Product: "Customer Engagement Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "LaunchDarkly",
    foundedYear: 2014,
    HQ: "Oakland, CA, USA",
    Industry: "Feature Management",
    totalFunding: "$330M",
    ARR: "$100M",
    Valuation: "$3B",
    Employees: 350,
    topInvestors: "Bessemer, Redpoint",
    Product: "Feature Management Platform",
    g2Rating: 4.7,
  },
  {
    companyName: "Gusto",
    foundedYear: 2011,
    HQ: "San Francisco, CA, USA",
    Industry: "HR & Payroll",
    totalFunding: "$516M",
    ARR: "$500M",
    Valuation: "$9.5B",
    Employees: "2,500",
    topInvestors: "General Catalyst, CapitalG",
    Product: "HR & Payroll Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Rippling",
    foundedYear: 2016,
    HQ: "San Francisco, CA, USA",
    Industry: "HR & IT",
    totalFunding: "$1.2B",
    ARR: "$350M",
    Valuation: "$13.5B",
    Employees: "2,000",
    topInvestors: "Founders Fund, Greenoaks",
    Product: "Employee Management Platform",
    g2Rating: 4.8,
  },
  {
    companyName: "Carta",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "Equity Management",
    totalFunding: "$1.1B",
    ARR: "$300M",
    Valuation: "$7.4B",
    Employees: "1,600",
    topInvestors: "Andreessen Horowitz, Lightspeed",
    Product: "Equity Management Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Plaid",
    foundedYear: 2013,
    HQ: "San Francisco, CA, USA",
    Industry: "Financial APIs",
    totalFunding: "$734M",
    ARR: "$400M",
    Valuation: "$13.4B",
    Employees: 800,
    topInvestors: "NEA, Spark Capital",
    Product: "Financial Data Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Marqeta",
    foundedYear: 2010,
    HQ: "Oakland, CA, USA",
    Industry: "Card Issuing",
    totalFunding: "$528M",
    ARR: "$717M",
    Valuation: "$4.3B",
    Employees: 900,
    topInvestors: "ICONIQ, Goldman Sachs",
    Product: "Card Issuing Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Affirm",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "BNPL",
    totalFunding: "$1.5B",
    ARR: "$1.6B",
    Valuation: "$12B",
    Employees: "2,500",
    topInvestors: "Founders Fund, Lightspeed",
    Product: "Buy Now Pay Later Platform",
    g2Rating: 4.1,
  },
  {
    companyName: "Ramp",
    foundedYear: 2019,
    HQ: "New York, NY, USA",
    Industry: "Expense Management",
    totalFunding: "$1.2B",
    ARR: "$300M",
    Valuation: "$8.1B",
    Employees: 500,
    topInvestors: "Thrive Capital, Founders Fund",
    Product: "Finance Platform",
    g2Rating: 4.8,
  },
  {
    companyName: "Brex",
    foundedYear: 2017,
    HQ: "San Francisco, CA, USA",
    Industry: "Corporate Cards",
    totalFunding: "$1.5B",
    ARR: "$400M",
    Valuation: "$12.3B",
    Employees: "1,100",
    topInvestors: "DST Global, Ribbit Capital",
    Product: "Financial Platform",
    g2Rating: 4.6,
  },
  {
    companyName: "Navan",
    foundedYear: 2015,
    HQ: "Palo Alto, CA, USA",
    Industry: "Travel & Expense",
    totalFunding: "$1.5B",
    ARR: "$400M",
    Valuation: "$9.2B",
    Employees: "2,500",
    topInvestors: "Andreessen Horowitz, Addition",
    Product: "Travel & Expense Platform",
    g2Rating: 4.7,
  },
  {
    companyName: "Benchling",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "Life Sciences R&D",
    totalFunding: "$425M",
    ARR: "$100M",
    Valuation: "$6.1B",
    Employees: 600,
    topInvestors: "Altimeter, Lux Capital",
    Product: "Life Sciences R&D Platform",
    g2Rating: 4.6,
  },
  {
    companyName: "Celonis",
    foundedYear: 2011,
    HQ: "Munich, Germany",
    Industry: "Process Mining",
    totalFunding: "$1.4B",
    ARR: "$600M",
    Valuation: "$13B",
    Employees: "3,000",
    topInvestors: "Arena Holdings, Durable Capital",
    Product: "Process Mining Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Redis",
    foundedYear: 2011,
    HQ: "Mountain View, CA, USA",
    Industry: "Database",
    totalFunding: "$347M",
    ARR: "$100M",
    Valuation: "$2B",
    Employees: 800,
    topInvestors: "Tiger Global, Softbank",
    Product: "In-Memory Database",
    g2Rating: 4.5,
  },
  {
    companyName: "Algolia",
    foundedYear: 2012,
    HQ: "San Francisco, CA, USA",
    Industry: "Search & Discovery",
    totalFunding: "$334M",
    ARR: "$100M",
    Valuation: "$2.3B",
    Employees: 700,
    topInvestors: "Accel, Salesforce Ventures",
    Product: "Search & Discovery API",
    g2Rating: 4.6,
  },
  {
    companyName: "Samsara",
    foundedYear: 2015,
    HQ: "San Francisco, CA, USA",
    Industry: "IoT",
    totalFunding: "$930M",
    ARR: "$856M",
    Valuation: "$12B",
    Employees: "2,100",
    topInvestors: "Andreessen Horowitz, Tiger",
    Product: "Connected Operations Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Verkada",
    foundedYear: 2016,
    HQ: "San Mateo, CA, USA",
    Industry: "Physical Security",
    totalFunding: "$460M",
    ARR: "$400M",
    Valuation: "$3.2B",
    Employees: "1,600",
    topInvestors: "Sequoia, Felicis",
    Product: "Cloud Security Platform",
    g2Rating: 4.7,
  },
  {
    companyName: "JFrog",
    foundedYear: 2008,
    HQ: "Sunnyvale, CA, USA",
    Industry: "DevOps",
    totalFunding: "$228.5M",
    ARR: "$265M",
    Valuation: "$5.7B",
    Employees: "1,000",
    topInvestors: "Insight Partners, Qumra",
    Product: "DevOps Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "Netskope",
    foundedYear: 2012,
    HQ: "Santa Clara, CA, USA",
    Industry: "Cloud Security",
    totalFunding: "$1.4B",
    ARR: "$500M",
    Valuation: "$7.5B",
    Employees: "2,500",
    topInvestors: "Sequoia, Lightspeed",
    Product: "SASE Platform",
    g2Rating: 4.6,
  },
  {
    companyName: "OneTrust",
    foundedYear: 2016,
    HQ: "Atlanta, GA, USA",
    Industry: "Privacy & Security",
    totalFunding: "$920M",
    ARR: "$500M",
    Valuation: "$5.3B",
    Employees: "2,500",
    topInvestors: "Generation IM, Insight",
    Product: "Trust Intelligence Platform",
    g2Rating: 4.3,
  },
  {
    companyName: "Tanium",
    foundedYear: 2007,
    HQ: "Kirkland, WA, USA",
    Industry: "Endpoint Management",
    totalFunding: "$1B",
    ARR: "$500M",
    Valuation: "$9.5B",
    Employees: "2,000",
    topInvestors: "Andreessen Horowitz, IVP",
    Product: "Endpoint Management Platform",
    g2Rating: 4.2,
  },
  {
    companyName: "Rubrik",
    foundedYear: 2014,
    HQ: "Palo Alto, CA, USA",
    Industry: "Data Security",
    totalFunding: "$750M",
    ARR: "$600M",
    Valuation: "$6B",
    Employees: "2,600",
    topInvestors: "Lightspeed, Greylock",
    Product: "Zero Trust Data Security",
    g2Rating: 4.6,
  },
  {
    companyName: "AppDynamics",
    foundedYear: 2008,
    HQ: "San Francisco, CA, USA",
    Industry: "APM",
    totalFunding: "$315M",
    ARR: "$600M",
    Valuation: "$3.7B (Cisco)",
    Employees: "2,000",
    topInvestors: "Lightspeed, Greylock",
    Product: "Application Performance Monitoring",
    g2Rating: 4.3,
  },
  {
    companyName: "Snyk",
    foundedYear: 2015,
    HQ: "Boston, MA, USA",
    Industry: "Developer Security",
    totalFunding: "$1.4B",
    ARR: "$200M",
    Valuation: "$7.4B",
    Employees: "1,300",
    topInvestors: "Tiger Global, Accel",
    Product: "Developer Security Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "CircleCI",
    foundedYear: 2011,
    HQ: "San Francisco, CA, USA",
    Industry: "CI/CD",
    totalFunding: "$315M",
    ARR: "$100M",
    Valuation: "$1.7B",
    Employees: 500,
    topInvestors: "IVP, DFJ Growth",
    Product: "CI/CD Platform",
    g2Rating: 4.4,
  },
  {
    companyName: "ServiceTitan",
    foundedYear: 2012,
    HQ: "Glendale, CA, USA",
    Industry: "Field Service",
    totalFunding: "$1.5B",
    ARR: "$685M",
    Valuation: "$9.5B",
    Employees: "2,700",
    topInvestors: "Tiger Global, Sequoia",
    Product: "Field Service Management",
    g2Rating: 4.2,
  },
  {
    companyName: "Procore",
    foundedYear: 2002,
    HQ: "Carpinteria, CA, USA",
    Industry: "Construction",
    totalFunding: "$899M",
    ARR: "$943M",
    Valuation: "$9B",
    Employees: "3,200",
    topInvestors: "Bessemer, Tiger Global",
    Product: "Construction Management Platform",
    g2Rating: 4.5,
  },
  {
    companyName: "Automattic",
    foundedYear: 2005,
    HQ: "San Francisco, CA, USA",
    Industry: "Web Publishing",
    totalFunding: "$987M",
    ARR: "$400M",
    Valuation: "$7.5B",
    Employees: "2,000",
    topInvestors: "Salesforce Ventures, Insight",
    Product: "WordPress.com, WooCommerce",
    g2Rating: 4.4,
  },
  {
    companyName: "Vimeo",
    foundedYear: 2004,
    HQ: "New York, NY, USA",
    Industry: "Video Platform",
    totalFunding: "$450M",
    ARR: "$433M",
    Valuation: "$1.5B",
    Employees: "1,200",
    topInvestors: "Thrive Capital, IAC",
    Product: "Video Platform",
    g2Rating: 4.2,
  },
];
